name: 'lcov-action'
description: 'Action to run lcov'
color: 'blue'
icon: 'check-square'
inputs:
    gcov_path:
        description: 'Path to gcov (github uses GCC 7.5.0)'
        required: true
        default: '/usr/bin/gcov'
    remove_patterns:
        description: 'Remove patterns, comma separated'
        required: true
        default: ''
    output_lcov_info:
        description: 'Output lcov info file'
        required: true
        default: 'coverage.info'
runs:
    using: 'docker'
    image: 'Dockerfile'
