name: 'lcov-action'
description: 'lcov action to run lcov'
inputs:
    gcov_path:
        description: 'Path to gcov (github uses GCC 7.5.0)'
        required: true
        default: '/usr/bin/gcov'
    params:
        description: 'lcov parameters'
        required: true
        default: ''
runs:
    using: 'docker'
    image: 'Dockerfile'
