on: [push, pull_request]
name: Build and Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Docker Build
      run: |
        docker build -t 2lcov-action .
